darcyflow_pdebench:
  dataset:
    train:
      dataset_path: ./PDE/data/DarcyFlow/PDEBench/2D_DarcyFlow_beta1.0_Train/train
      n_all_samples: 9000  # 9000
      resolution: 64
      reduced_resolution: 2
      reduced_batch: 1
      batch_size: 8
    test:
      dataset_path: ./PDE/data/DarcyFlow/PDEBench/2D_DarcyFlow_beta1.0_Train/test
      n_all_samples: 1000 # 1000
      resolution: 64
      reduced_resolution: 2
      reduced_batch: 1
      batch_size: 8
  save_path: runs/darcyflow_pdebench
  additional_str: Stanx2
  epochs: 100
  seed: 42
  lr: 0.001
  in_seq_len: null
  out_seq_len: null
  node_feats: 1
  pos_dim: 2
  n_targets: 1
  n_hidden: 256
  num_feat_layers: 0
  num_encoder_layers: 6
  n_head: 4
  dim_feedforward: 256
  feat_extract_type: null
  attention_type: mamba
  xavier_init: 0.01
  diagonal_weight: 0.01
  symmetric_init: False
  layer_norm: False
  attn_norm: True
  norm_eps: 0.0000001
  batch_norm: False
  return_attn_weight: False
  return_latent: False
  decoder_type: ifft2
  spacial_dim: 2
  spacial_fc: True
  downscaler_size: null
  upscaler_size: null
  upsample_mode: interp
  downsample_mode: interp
  freq_dim: 32
  boundary_condition: dirichlet
  num_regressor_layers: 2
  fourier_modes: 12
  regressor_activation: silu
  downscaler_activation: relu
  upscaler_activation: silu
  last_activation: True
  dropout: 0.0
  downscaler_dropout: 0.0
  upscaler_dropout: 0.0
  ffn_dropout: 0.0
  encoder_dropout: 0.0
  decoder_dropout: 0.0
  debug: False
  ssm_d_state: 16
  ssm_ratio: 2.0
  ssm_rank_ratio: 2.0
  forward_type: "v2"
