dr2d_pdebench:
  dataset:
    train:
      dataset_path: ./PDE/data/DiffusionReaction/PDEBench/npz/train
      n_all_samples: 900  # 900
      reduced_resolution: 2
      reduced_resolution_t: 1
      reduced_batch: 1
      in_seq: 10
      out_seq: 91
      batch_size: 4
      normalize_y: unit
    test:
      dataset_path: ./PDE/data/DiffusionReaction/PDEBench/npz/test
      n_all_samples: 100 # 100
      reduced_resolution: 2
      reduced_resolution_t: 1
      reduced_batch: 1
      in_seq: 10
      out_seq: 91
      batch_size: 4
      normalize_y: unit
  save_path: runs/dr2d_pdebench
  additional_str: Cx2
  epochs: 100
  seed: 42
  lr: 0.001
  in_seq_len: 10
  out_seq_len: 91
  node_feats: 20
  pos_dim: 2
  n_targets: 182
  n_hidden: 256
  num_feat_layers: 0
  num_encoder_layers: 6
  n_head: 4
  dim_feedforward: 256
  feat_extract_type: null
  attention_type: softmax
  xavier_init: 0.01
  diagonal_weight: 0.01
  symmetric_init: False
  layer_norm: False
  attn_norm: True
  norm_eps: 0.0000001
  batch_norm: False
  return_attn_weight: False
  return_latent: False
  decoder_type: ifft2
  spacial_dim: 2
  spacial_fc: True
  downscaler_size: null
  upscaler_size: null
  upsample_mode: interp
  downsample_mode: interp
  freq_dim: 32
  boundary_condition: dirichlet
  num_regressor_layers: 2
  fourier_modes: 12
  regressor_activation: silu
  downscaler_activation: relu
  upscaler_activation: silu
  last_activation: True
  dropout: 0.0
  downscaler_dropout: 0.0
  upscaler_dropout: 0.0
  ffn_dropout: 0.0
  encoder_dropout: 0.0
  decoder_dropout: 0.0
  debug: False

